modLoader="javafml"
loaderVersion="[49,)"
license="MIT License"
[[mods]]
modId="poorgolems"
version="${file.jarVersion}"
displayName="Poor Golems Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/poor-golems"
displayTest="IGNORE_SERVER_VERSION"
updateJSONURL="https://github.com/mactso/PoorGolems/raw/master/update.json"
logoFile="logo.png"
authors="MacTso, Lupicus"
description='Poor Golems.'
[[dependencies.poorgolems]]
    modId="forge"
    mandatory=true
    versionRange="[49,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.poorgolems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"
